defaults:
  - _self_
  - dataset: calvin
  - model: DAWN_stage1

project: DAWN-motion-director
save_dir: ./outputs_new
resume: false
desc: hsv-bs16-skip10-lr1e-4-total50k-cont
debug: false
seed: 0

weights: #null 
  model: /home/ero/Projects/DAWN/outputs/DAWN-action-expert/2026-04-01_01-49/checkpoints/model_0035000.pth
  motion_director: /home/ero/Projects/DAWN/outputs/DAWN-motion-director/2026-03-13_14-08/checkpoints/model_final.pth
  
trainer:
  accumulate: 1
  total_steps: 50000
  log_interval: 20
  save_interval: 1000
  val_interval: 500
  save_dir: '${save_dir}/${project}/${desc}/${now:%Y-%m-%d_%H-%M}'
  resume: ${resume}
  lr_warmup_steps: 10

accelerator: 
  gradient_accumulation_steps: ${trainer.accumulate}
  mixed_precision: fp16
  log_with: wandb
  project_dir: ${trainer.save_dir}

loader:
  train_batch_size: 16
  val_batch_size: 16
  num_workers: 4

optimizer:
  _target_: 'torch.optim.AdamW'
  lr: 1e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]

